export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_USER_BY_ID= "GET_USER_BY_ID"
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const GET_POST_BY_CATEGORY = "GET_POST_BY_CATEGORY"
export const GET_POST_BY_PROVINCE = "GET_POST_BY_PROVINCE"
export const GET_POST_BY_LOCALITY = "GET_POST_BY_LOCALITY"
export const SELECT_CATEGORY = "SELECT_CATEGORY"
export const SELECT_PROVINCE = "SELECT_PROVINCE";
export const SELECT_LOCALITY = "SELECT_LOCALITY";
export const CREATE_POST = "CREATE_POST"
export const CLEAR_DETAIL = "CLEAR_DETAIL"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const SELECTED_POST = "SELECTED_POST"
export const RESET_FILTERS = "RESET_FILTERS"

export const LIKE_POST = "LIKE_POST"
export const GET_MATCHES = "GET_MATCHES"
export const UPDATE_FILTERED_MATCHES = "UPDATE_FILTERED_MATCHES"

export const CARGAR_HISTORIAL_MENSAJES = "CARGAR_HISTORIAL_MENSAJES"
export const ADD_MESSAGE_TO_HISTORY = "ADD_MESSAGE_TO_HISTORY"
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES"
export const GET_ALL_CHATS = "GET_ALL_CHATS"