export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_DISABLED_USERS = "GET_ALL_DISABLED_USERS";
export const GET_ALL_EXISTING_USERS = "GET_ALL_EXISTING_USERS";
export const GET_USER_BY_ID= "GET_USER_BY_ID"
export const SORT_USER_BY_ID= "SORT_USER_BY_ID"
export const SORT_USER_BY_PLAN= "SORT_USER_BY_PLAN"
export const SORT_USER_BY_STATUS= "SORT_USER_BY_STATUS"
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const RESTORE_USER = "RESTORE_USER";
export const RESET_USERS_FILTER = "RESET_USERS_FILTER";


export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_DISABLED_POSTS = "GET_ALL_DISABLED_POSTS";
export const GET_ALL_EXISTING_POSTS = "GET_ALL_EXISTING_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const SORT_POSTS_BY_ID= "SORT_POSTS_BY_ID"
export const SORT_POSTS_BY_STATUS= "SORT_POSTS_BY_STATUS"
export const GET_POST_BY_CATEGORY = "GET_POST_BY_CATEGORY"
export const GET_POST_BY_PROVINCE = "GET_POST_BY_PROVINCE"
export const GET_POST_BY_LOCALITY = "GET_POST_BY_LOCALITY"
export const RESET_POSTS_FILTER = "RESET_POSTS_FILTER";
export const SELECT_CATEGORY = "SELECT_CATEGORY"
export const SELECT_PROVINCE = "SELECT_PROVINCE";
export const SELECT_LOCALITY = "SELECT_LOCALITY";
export const CREATE_POST = "CREATE_POST"
export const CLEAR_DETAIL = "CLEAR_DETAIL"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const RESTORE_POST = "RESTORE_POST"
export const SELECTED_POST = "SELECTED_POST"
export const RESET_FILTERS = "RESET_FILTERS"

export const LIKE_POST = "LIKE_POST"
export const GET_ALL_LIKES = "GET_ALL_LIKES"
export const DELETE_LIKE = "DELETE_LIKE"
export const LIKED_POSTS = "LIKED_POSTS"

export const GET_MATCHES = "GET_MATCHES"
export const UPDATE_FILTERED_MATCHES = "UPDATE_FILTERED_MATCHES"

export const CARGAR_HISTORIAL_MENSAJES = "CARGAR_HISTORIAL_MENSAJES"
export const OTHER_USER_DATA = "OTHER_USER_DATA"
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES"
export const CREATE_MESSAGE = "CREATE_MESSAGES"
export const GET_ALL_CHATS = "GET_ALL_CHATS"
export const ADD_REVIEW = "ADD_REVIEW"
export const CHAT_CREATED = "CHAT_CREATED"
