export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_USER_BY_ID= "GET_USER_BY_ID"
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const GET_POST_BY_CATEGORY = "GET_POST_BY_CATEGORY"
export const GET_POST_BY_PROVINCE = "GET_POST_BY_PROVINCE"
export const GET_POST_BY_LOCALITY = "GET_POST_BY_LOCALITY"
export const SELECT_CATEGORY = "SELECT_CATEGORY"
export const SELECT_PROVINCE = "SELECT_PROVINCE";
export const SELECT_LOCALITY = "SELECT_LOCALITY";
export const CREATE_POST = "CREATE_POST"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const RESET_FILTERS = "RESET_FILTERS"